### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by sjchmiela**
- removes goreleaser, Cirrus workflow — instead adds GHA workflow
- removes all Sentry references

### CODE REVIEW

**Comment by sjchmiela** [comment]
Sorry, Github defaults haha

**Comment by fkorotkov** [comment]
@sjchmiela FYI Softnet is licensed under AGPL-3.0. So in case you have a private fork with modifications, they should be made publicly available.

**Comment by sjchmiela** [comment]
👍 I wanted to let VMs contact non-global IPs (remove [this](https://github.com/cirruslabs/softnet/blob/cd5f1d2f4f0d8fd7c646d6a0c88d8539939750fe/lib/proxy/vm.rs#L64-L66)), but wasn't sure if softnet-sofnet would benefit from this change, so I set up a fork. Let me know if you think it would make sense to upstream this change, behind a flag or something!

**Comment by fkorotkov** [comment]
One of the points of AGPL license is not particularly to always contribute back but in general have all the modifications in the open. This way the whole community of the project can see what people do around and potentially cherry pick changes. Ultimately this knowledge sharing should make the project better.

**Pull request closed without merging**
